// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLtTCSxKLlSUW_b3Qj4kfZ-c_aHEBxp8',
    appId: '1:996322536000:web:c4bd72ee05ce75281f4da5',
    messagingSenderId: '996322536000',
    projectId: 'jansuraksha-876ef',
    authDomain: 'jansuraksha-876ef.firebaseapp.com',
    storageBucket: 'jansuraksha-876ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhTgSe9fiumMHRcfrP4Updj93yUsMI18',
    appId: '1:996322536000:android:5ef819e04dcef4851f4da5',
    messagingSenderId: '996322536000',
    projectId: 'jansuraksha-876ef',
    storageBucket: 'jansuraksha-876ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gJrUNAmes8fHQPV220T_rOCJAS4mTRw',
    appId: '1:996322536000:ios:cf4883951ce98cd71f4da5',
    messagingSenderId: '996322536000',
    projectId: 'jansuraksha-876ef',
    storageBucket: 'jansuraksha-876ef.firebasestorage.app',
    iosClientId: '996322536000-kfsthi9ig141sis696rvsjn69jc6f8b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jansuraksha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLtTCSxKLlSUW_b3Qj4kfZ-c_aHEBxp8',
    appId: '1:996322536000:web:2860d81f477d5e091f4da5',
    messagingSenderId: '996322536000',
    projectId: 'jansuraksha-876ef',
    authDomain: 'jansuraksha-876ef.firebaseapp.com',
    storageBucket: 'jansuraksha-876ef.firebasestorage.app',
  );
}
